---
site:
  title: kaashif's blog
  author: Kaashif Hymabaccus
  tagline: Computers, with some mathematics on the side
  url: https://kaashif.co.uk
  uploadcmd: rsync -rvz site/ kaashif.co.uk:/var/www/htdocs/kaashif.co.uk/
  extrafiles:
    - css
    - keybase.txt
    - favicon.ico
