---
site:
  title: kaashif's blog
  author: Kaashif Hymabaccus
  tagline: Programming, software freedom and Unix
  url: http://www.kaashif.co.uk
  uploadcmd: rsync -rvz site/ kaashif.co.uk:/var/www/htdocs/
  extrafiles:
    - css
    - keybase.txt
    - favicon.ico
