<!DOCTYPE html>
<html>
<head>
<title>$title$</title>
<style>
@import url(http://fonts.googleapis.com/css?family=Lato);
html {
	background: #FFFFFF;
}

body {
	padding: 50px 0;
	margin: 0;
	font-family: 'Lato', Helvetica, sans-serif;
	color: #555;
	font-weight: 300;
}

.wrapper {
	max-width: 640px;
	margin: 0 auto;
	background: #FFFFFF;
	border-radius: 8px;
}

header, section, footer {
	display: block;
}

a {
	color: #2D2E2F;
	text-decoration: none;
}

p {
	margin: 0 0 20px;
	padding: 0;
}

strong {
	color: #222;
	font-weight: 700;
}

header {
	border-radius: 8px 8px 0 0;
	background: #FFFFFF;
	position: relative;
	padding: 20px 20px 30px 20px;
	margin-top: -1px;
}

header h1 {
	margin: 0;
	padding: 0;
	font-size: 24px;
	line-height: 1.2;
	color: #2D2E2F;
}
header p {
	margin: 0;
	color: #2D2E2F;
	font-size: 15px;
}
header ul {
	float: left;
	list-style: none;
	margin-left: -45px;
}
header ul li {
	float: left;
	padding: 13px 5px;
}
main {
	font-size: 15px;
	border-top: 1px solid #fff;
	position: relative;
	border-radius: 8px;
}

.content {
	padding: 15px 20px 20px 20px;
}

h1, h2, h3, h4, h5, h6 {
	color: #666;
	padding: 0;
	margin: 0 0 20px;
	line-height: 1.2;
}

p, ul, ol, table, pre, dl {
	margin: 0 0 20px;
}

h1, h2, h3 {
	line-height: 1.1;
}

h1 {
	font-size: 28px;
	color: #2D2E2F;
}

h2 {
	color: #2D2E2F;
}

h3, h4, h5, h6 {
	color: #494949;
}

blockquote {
	margin: 0 -20px 20px;
	padding: 15px 20px 1px 40px;
	font-style: italic;
	background: #ccc;
	background: rgba(0, 0, 0, 0.06);
	color: #222;
}

img {
	max-width:100%;
	display: block;
	margin-left: auto;
	margin-right: auto;
}

code, pre {
	color: #333;
	font-size: 12px;
}

pre {
	padding: 20px;
	background: #272822;
	color: #DDD;
	margin: 0px;
	margin-bottom: 20px;
	overflow-x:auto;
}

li pre {
	margin-left: -60px;
	padding-left: 60px;
}

table {
	width: 100%;
	border-collapse: collapse;
}

th, td {
	text-align: left;
	padding: 5px 10px;
	padding-top: 10px;
	padding-bottom: 10px;
	border-bottom: 1px solid #aaa;
}

td + td {
	max-width: 200px;
}

dt {
	color: #222;
	font-weight: 700;
}

th {
	color: #222;
}

small {
	font-size: 11px;
}

hr {
	background: #aaa;
	margin: 0 0 20px;
}

footer {
	width: 640px;
	margin: 0 auto;
	padding: 20px 0 0;
	color: #aaa;
	overflow: hidden;
}
footer a {
	color: #bbb;
	font-weight: bold;
}
footer p {
	float: left;
}
footer p + p {
	float: right;
}
</style>
<link rel="stylesheet" type="text/css" href="/static/monokai.css" />
<script type="text/javascript"
  src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>
<script type="text/javascript" src="/static/highlight.js"></script>
<script type="text/javascript">hljs.initHighlightingOnLoad();</script>
<meta name=viewport content="width=device-width, initial-scale=1">
</head>
<body>
<div class="wrapper">
<main>
<header>
        <h1>$site.title$</h1>
        <p>$site.tagline$</p>
        <ul>
            <li> <a href="/home">Home</a></li>
            <li>//</li>
            <li> <a href="/about">About</a></li>
            <li>//</li>
            <li> <a href="/contact">Contact</a></li>
            <li>//</li>
            <li> <a href="/archive">Archive</a></li>
            <li>//</li>
            <li> <a href="http://code.kaashif.co.uk/">Code</a></li>
        </ul>
</header>
<hr style="clear: both; visibility: hidden;" />
<div class="content">
